//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPCUAServer.SE.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPCUAServer.SE.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start ControllerNodeManager..
        /// </summary>
        internal static string ControllerNodeManagerFailed {
            get {
                return ResourceManager.GetString("ControllerNodeManagerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Node Managers..
        /// </summary>
        internal static string CreatingNodeManagers {
            get {
                return ResourceManager.GetString("CreatingNodeManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &lt;enter&gt; to exit the program..
        /// </summary>
        internal static string ExitProgramMessage {
            get {
                return ResourceManager.GetString("ExitProgramMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop ControllerNodeManager..
        /// </summary>
        internal static string FailedToStopControllerNodeManager {
            get {
                return ResourceManager.GetString("FailedToStopControllerNodeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening at the following endpoints:.
        /// </summary>
        internal static string ListeningAtEndPoints {
            get {
                return ResourceManager.GetString("ListeningAtEndPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the Controller Model..
        /// </summary>
        internal static string LoadControllerModelMessage {
            get {
                return ResourceManager.GetString("LoadControllerModelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move certificate {0} [{1}].der from {2}\\certs to {3}\\certs to accept.
        /// </summary>
        internal static string MoveCertificate {
            get {
                return ResourceManager.GetString("MoveCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting ControllerNodeManager..
        /// </summary>
        internal static string StartControllerMessage {
            get {
                return ResourceManager.GetString("StartControllerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Server..
        /// </summary>
        internal static string StartingServer {
            get {
                return ResourceManager.GetString("StartingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Status={1}.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping ControllerNodeManager..
        /// </summary>
        internal static string StoppingControllerNodeManager {
            get {
                return ResourceManager.GetString("StoppingControllerNodeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Server..
        /// </summary>
        internal static string StoppingServer {
            get {
                return ResourceManager.GetString("StoppingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrusted Certificate: {0}, {1}.
        /// </summary>
        internal static string UntrustedCertificate {
            get {
                return ResourceManager.GetString("UntrustedCertificate", resourceCulture);
            }
        }
    }
}
